
config {
    type: "incremental",
    name: "data_jobs",
    tags: ['incremental'],
    dependencies: ["part_messages"],
    bigquery: {
        partitionBy: "DATE_TRUNC(date, MONTH)",
        updatePartitionFilter: "date >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)"
    },

}

js {
  const trashRegex = '(?:подборка|bootcamp|меня зовут|my name|вебинар|буткемп|webinar|прокачайтесь|курс\b|skillbox|гайд|реклама|карьерный план|#резюме|#resume|#cv|отправлю резюме)[^\n]*'
  const dataJobRegex = '(dataops|data\s*[)-–—]*\s*op|dwh\s*[)-–—]*\s*engineer|data\s*[)-–—]*\s*engineer|дата\s*[)-–—]*\s*инженер|инженер\s*[)-–—]*\s*данных|инженер\s*[)-–—]*\s*по\s*[)-–—]*\s*данным|data\s*[)-–—]*\s*инженер|data\s*[)-–—]*\s*engineer|dataengineer|data.*python|data.*ruby|data\s*[)-–—]*\s*software|software\s*[)-–—]*\s*data|data\s*[)-–—]*\s*analyst|marketing\s*[)-–—]*\s*analyst|data\s*[)-–—]*\s*аналитик|engineering\s*[)-–—]*\s*analyst|analytics\s*[)-–—]*\s*engineer)';
}

SELECT
    ts,
    date,
    link,
    text,
    TRUE AS is_data_job
FROM 
    ${ref('part_messages')} t
WHERE TRUE
    ${when(incremental(), `
        AND date >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
        AND ts > (SELECT MAX(ts) FROM ${self()})
    `)}
    AND empty IS NOT NULL 
    AND text IS NOT NULL 
    AND text != ''
    AND NOT REGEXP_CONTAINS(LOWER(text), r"""${trashRegex}""") 
    AND REGEXP_CONTAINS(LOWER(text), r"""${dataJobRegex}""") 
